apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- envVariables.yaml
- resourceLimits.yaml
- scalingMetrics.yaml
- hpa.yaml
resources:
- ../../../base/echoservice

