apiVersion: v1
kind: Service
metadata:
  name: user-roles
  namespace: user-mgmt
  labels:
    app: user-roles
    version: "v1"
    backstage.io/kubernetes-id: user-roles
spec:
  selector:
    app: user-roles
  ports:
    - name: http-80
      port: 8080
      protocol: TCP
      targetPort: 5001