apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: static-infra
  namespace: flux-system
spec:
  interval: 1m0s
  dependsOn:
  - name: sources
  - name: namespaces
  - name: gatekeeper-install
  - name: cert-manager-install
  - name: kiali-install
  - name: istio-install
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/static
  prune: true