apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoservice
  namespace: default
  labels:
    app: echoservice
    version: "v1"
spec:
  selector:
    matchLabels:
      app: echoservice
  template:
    metadata:
      labels:
        app: echoservice
        version: "v1"
    spec:
      containers:
      - image: k8s.gcr.io/e2e-test-images/echoserver:2.5
        imagePullPolicy: Always
        name: echoservice
        ports:
        - containerPort: 8080
        livenessProbe:
          initialDelaySeconds: 1
          periodSeconds: 2
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 1
          httpGet:
            scheme: HTTP
            path: /
            port: 8080