apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: kustomized-infra
    - name: sources
    - name: static-infra
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/overlays/development
  prune: true
  wait: true
  timeout: 1m0s