apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: redis-install
  namespace: flux-system
spec:
  interval: 1m0s
  dependsOn:
  - name: sources
  - name: namespaces
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/static/redis/install
  prune: true 