apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: user-roles
  namespace: user-mgmt
  labels:
    backstage.io/kubernetes-id: user-roles
spec:
  minReplicas: 1
  maxReplicas: 1
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 90
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80