apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - echoservice
  - user-roles
patches:
  - target:
      kind: ImageRepository
      name: .*
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: flux-system
  - target:
      kind: ImagePolicy
      name: .*
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: flux-system
  - target:
      kind: Deployment
      name: echoservice
    patch: |-
      - op: remove
        path: /spec/template/spec/containers/0/securityContext