---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: user-roles
  namespace: user-mgmt
spec:
  imageRepositoryRef:
    name: user-roles
  filterTags:
    pattern: 'production-v(?P<version>.*)'
    extract: '$version'
  policy:
    semver:
      range: '>0.0.1'

