apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-roles
  namespace: user-mgmt
  labels:
    app: user-roles
    version: "v1"
spec:
  template:
    spec:
      containers:
      - name: user-roles
        resources:
          limits:
            memory: 128Mi
            cpu: "500m"
          requests:
            memory: 64Mi
            cpu: "100m"
        env:
        - name: MEM_TOTAL_MB
          valueFrom:
            resourceFieldRef:
              resource: limits.memory