apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: user-roles
  namespace: user-mgmt
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: user-roles
  minReplicas: 1
  maxReplicas: 1
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 90