apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: aws-load-balancer-controller
  namespace: flux-system
spec:
  releaseName: aws-load-balancer-controller
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  chart:
    spec:
      version: "2.7.1"
      chart: aws-load-balancer-controller
      sourceRef:
        kind: HelmRepository
        name: eks-charts
  interval: 1h0m0s
  values:
    clusterName: patchedByOverlay
    serviceAccount:
      create: false
      name: aws-load-balancer-controller
  targetNamespace: kube-system